version: "3"

services:
  node:
    image: ethereum/client-go:alltools-release-1.8
    ports:
      - 8544-8546:8544-8546
    volumes:
      - ./scripts:/scripts:ro
      - ./keystore:/keystore:ro
    command: /scripts/node.sh